### ISSUE TITLE
[DOC] Fix Link

### ISSUE THREAD

**Issue by Akshu-on-github** [Akshu-on-github/github-actions-starter-kit#2]
<img src = "https://user-images.githubusercontent.com/61582763/137442596-5e7db37b-165c-43b4-8416-4aba60d0b6ed.png" width=50% align = "right">

## Description
The `<details>` tag overrides the HTML

## TODO:
- [ ] Convert the Markdown into HTML

**Comment by Prashant0kgp** [comment]
HI, @Akshu-on-github plz, assign me I want to work on it under hacktoberfest labels
thank you!

**Comment by Akshu-on-github** [comment]
Go ahead @Prashant0kgp!
